const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

// Differential parity against the real Gauge parser, frozen as a fixture.
//
// Every entry in test/fixtures/parser-parity.json carries a specification and
// the exact ParseError messages `parser.SpecParser.Parse` produces for it. The
// fixture was generated by running the real parser through a temporary Go module
// that does `replace github.com/getgauge/gauge => getgauge/gauge`; regenerate
// it the same way when adding cases, never by copying what this extension
// happens to output.
//
// This exists because hand-tuning the heading, table and doc string state machine
// against one case at a time, which is easy to get right for the case at hand and
// wrong for a shape fixed earlier. This corpus fails `npm run check` instead.
//
// Messages the parser does not model are excluded: Undefined Step and duplicate
// implementation come from the local Kotlin index, and Gauge reports the multiple
// data table case as a warning rather than a parse error.
const IGNORED_MESSAGES = new Set([
  "Undefined Step",
  "Multiple data table present, ignoring table",
  "Duplicate step implementation found",
]);

const IMPLEMENTATIONS = [
  "@Step(\"a\")",
  "fun a() {}",
  "@Step(\"b\")",
  "fun b() {}",
  "@Step(\"say <x>\")",
  "fun say(x: String) {}",
  "@Step(\"* a\")",
  "fun starA() {}",
  "@Step(\"text\")",
  "fun text() {}",
].join("\n");

function createDocument(text, languageId, fsPath) {
  return { languageId, uri: { fsPath }, getText: () => text };
}

function createVscode() {
  return {
    languages: {},
    workspace: {},
    window: {},
    Range: function Range(start, end) {
      this.start = start;
      this.end = end;
    },
    Position: function Position(line, character) {
      this.line = line;
      this.character = character;
    },
    Diagnostic: function Diagnostic(range, message, severity) {
      this.range = range;
      this.message = message;
      this.severity = severity;
    },
    DiagnosticSeverity: { Error: 0, Warning: 1 },
  };
}

function productMessages(text) {
  const { GaugeStepDiagnosticsProvider } = require("../src/stepDiagnostics");
  const spec = createDocument(text, "gauge", "/workspace/gauge/specs/a.spec");
  const implementation = createDocument(
    IMPLEMENTATIONS,
    "kotlin",
    "/workspace/gauge/src/test/kotlin/Steps.kt",
  );
  const documents = [spec, implementation];
  const provider = new GaugeStepDiagnosticsProvider({
    documentStore: {
      documents: () => documents,
      onDidChangeDocuments: () => ({ dispose() {} }),
      start() {},
    },
    projectFactory: {
      isGaugeProject: () => true,
      getGaugeRootFromFilePath: () => "/workspace/gauge",
    },
    fileSystem: {
      existsSync: () => false,
      readFileSync() {
        throw new Error("no project properties");
      },
      readdirSync() {
        throw new Error("no environment directory");
      },
    },
    pathModule: path.posix,
    vscode: createVscode(),
  });
  return provider
    .provideDiagnostics(spec, documents)
    .map((diagnostic) => diagnostic.message)
    .filter((message) => !IGNORED_MESSAGES.has(message))
    .filter((message) => !message.startsWith("Could not resolve special param"))
    .sort();
}

const corpus = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "parser-parity.json"), "utf8"),
);

test("diagnostics agree with the real Gauge parser across the parity corpus", () => {
  assert.ok(corpus.length >= 50, "the corpus must stay broad");
  const mismatches = [];
  for (const entry of corpus) {
    const actual = productMessages(entry.text);
    const expected = [...entry.parserErrors].sort();
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      mismatches.push({ label: entry.label, expected, actual });
    }
  }
  assert.deepEqual(mismatches, []);
});

// The concept half of the same corpus. Ground truth is
// parser.CreateConceptsDictionary against a temporary project holding the file,
// which is what the extension's concept diagnostics have to match.
const conceptCorpus = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "concept-parity.json"), "utf8"),
);

function conceptMessages(text) {
  const { GaugeStepDiagnosticsProvider } = require("../src/stepDiagnostics");
  const concept = createDocument(
    text,
    "gauge-concept",
    "/workspace/gauge/specs/concepts/c.cpt",
  );
  const implementation = createDocument(
    IMPLEMENTATIONS,
    "kotlin",
    "/workspace/gauge/src/test/kotlin/Steps.kt",
  );
  const documents = [concept, implementation];
  const provider = new GaugeStepDiagnosticsProvider({
    documentStore: {
      documents: () => documents,
      onDidChangeDocuments: () => ({ dispose() {} }),
      start() {},
    },
    projectFactory: {
      isGaugeProject: () => true,
      getGaugeRootFromFilePath: () => "/workspace/gauge",
    },
    fileSystem: {
      existsSync: () => false,
      readFileSync() {
        throw new Error("no project properties");
      },
      readdirSync() {
        throw new Error("no environment directory");
      },
    },
    pathModule: path.posix,
    vscode: createVscode(),
  });
  return provider
    .provideDiagnostics(concept, documents)
    .map((diagnostic) => diagnostic.message)
    .filter((message) => !IGNORED_MESSAGES.has(message))
    .filter((message) => !message.startsWith("Could not resolve special param"))
    .filter((message) => !message.startsWith("Circular reference found"))
    .sort();
}

test("concept diagnostics agree with the real Gauge concept parser", () => {
  assert.ok(conceptCorpus.length >= 30, "the concept corpus must stay broad");
  const mismatches = [];
  for (const entry of conceptCorpus) {
    const actual = conceptMessages(entry.text);
    const expected = [...entry.parserErrors].sort();
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      mismatches.push({ label: entry.label, expected, actual });
    }
  }
  assert.deepEqual(mismatches, []);
});

// The parser also says WHICH line each error is on, and a diagnostic on the wrong
// line sends the user to the wrong place. ParseError.LineNo is 1-based; VS Code
// ranges are 0-based.
//
// Messages the extension deliberately words differently, or reports at a
// different anchor than the parser's token, are listed here with the reason
// rather than silently skipped.
const LINE_EXEMPT_MESSAGES = new Set([
  // The parser anchors this at the spec heading; the extension anchors it at the
  // first content line, which is where the user has to add the heading.
  "Spec heading not found",
  // Anchored at the whole file, which has no single line.
  "Spec does not have any elements",
]);

function productDiagnostics(text) {
  const { GaugeStepDiagnosticsProvider } = require("../src/stepDiagnostics");
  const spec = createDocument(text, "gauge", "/workspace/gauge/specs/a.spec");
  const implementation = createDocument(
    IMPLEMENTATIONS,
    "kotlin",
    "/workspace/gauge/src/test/kotlin/Steps.kt",
  );
  const documents = [spec, implementation];
  const provider = new GaugeStepDiagnosticsProvider({
    documentStore: {
      documents: () => documents,
      onDidChangeDocuments: () => ({ dispose() {} }),
      start() {},
    },
    projectFactory: {
      isGaugeProject: () => true,
      getGaugeRootFromFilePath: () => "/workspace/gauge",
    },
    fileSystem: {
      existsSync: () => false,
      readFileSync() {
        throw new Error("no project properties");
      },
      readdirSync() {
        throw new Error("no environment directory");
      },
    },
    pathModule: path.posix,
    vscode: createVscode(),
  });
  return provider.provideDiagnostics(spec, documents);
}

// Every element of parserErrorLines is { line, message }: the parser's 1-based
// line and the message it belongs to. A bare line number carries no message, so
// it can never be matched to a diagnostic, and an expectation that cannot be
// matched has to fail rather than be dropped - a skipped expectation looks
// exactly like a passing one.
test("every line expectation in the corpus is one the test can check", () => {
  const malformed = [];
  for (const entry of corpus) {
    for (const error of entry.parserErrorLines || []) {
      if (
        !error
        || typeof error !== "object"
        || typeof error.message !== "string"
        || typeof error.line !== "number"
      ) {
        malformed.push({ label: entry.label, error });
      }
    }
  }
  assert.deepEqual(malformed, []);
});

test("diagnostics land on the line the real parser names", () => {
  const mismatches = [];
  const unmatched = [];
  for (const entry of corpus) {
    const expected = (entry.parserErrorLines || [])
      .filter((error) => !LINE_EXEMPT_MESSAGES.has(error.message));
    if (expected.length === 0) {
      continue;
    }
    const produced = productDiagnostics(entry.text);
    for (const error of expected) {
      const match = produced.find((diagnostic) => diagnostic.message === error.message);
      if (!match) {
        unmatched.push({ label: entry.label, message: error.message });
        continue;
      }
      if (match.range.start.line !== error.line - 1) {
        mismatches.push({
          label: entry.label,
          message: error.message,
          expectedLine: error.line - 1,
          actualLine: match.range.start.line,
        });
      }
    }
  }
  assert.deepEqual(unmatched, []);
  assert.deepEqual(mismatches, []);
});
