const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

// Differential parity against the real Gauge parser, frozen as a fixture.
//
// Every entry in test/fixtures/parser-parity.json carries a specification and
// the exact ParseError messages `parser.SpecParser.Parse` produces for it. The
// fixture was generated by running the real parser through a temporary Go module
// that does `replace github.com/getgauge/gauge => references/gauge`; regenerate
// it the same way when adding cases, never by copying what this extension
// happens to output.
//
// This exists because hand-tuning the heading, table and doc string state machine
// against one case at a time kept introducing regressions that only a later audit
// found. A regression here now fails `npm run check` instead.
//
// Messages the parser does not model are excluded: Undefined Step and duplicate
// implementation come from the local Kotlin index, and Gauge reports the multiple
// data table case as a warning rather than a parse error.
const IGNORED_MESSAGES = new Set([
  "Undefined Step",
  "Multiple data table present, ignoring table",
  "Duplicate step implementation found",
]);

const IMPLEMENTATIONS = [
  "@Step(\"a\")",
  "fun a() {}",
  "@Step(\"b\")",
  "fun b() {}",
  "@Step(\"say <x>\")",
  "fun say(x: String) {}",
  "@Step(\"* a\")",
  "fun starA() {}",
  "@Step(\"text\")",
  "fun text() {}",
].join("\n");

function createDocument(text, languageId, fsPath) {
  return { languageId, uri: { fsPath }, getText: () => text };
}

function createVscode() {
  return {
    languages: {},
    workspace: {},
    window: {},
    Range: function Range(start, end) {
      this.start = start;
      this.end = end;
    },
    Position: function Position(line, character) {
      this.line = line;
      this.character = character;
    },
    Diagnostic: function Diagnostic(range, message, severity) {
      this.range = range;
      this.message = message;
      this.severity = severity;
    },
    DiagnosticSeverity: { Error: 0, Warning: 1 },
  };
}

function productMessages(text) {
  const { GaugeStepDiagnosticsProvider } = require("../src/stepDiagnostics");
  const spec = createDocument(text, "gauge", "/workspace/gauge/specs/a.spec");
  const implementation = createDocument(
    IMPLEMENTATIONS,
    "kotlin",
    "/workspace/gauge/src/test/kotlin/Steps.kt",
  );
  const documents = [spec, implementation];
  const provider = new GaugeStepDiagnosticsProvider({
    documentStore: {
      documents: () => documents,
      onDidChangeDocuments: () => ({ dispose() {} }),
      start() {},
    },
    projectFactory: {
      isGaugeProject: () => true,
      getGaugeRootFromFilePath: () => "/workspace/gauge",
    },
    fileSystem: {
      existsSync: () => false,
      readFileSync() {
        throw new Error("no project properties");
      },
      readdirSync() {
        throw new Error("no environment directory");
      },
    },
    pathModule: path.posix,
    vscode: createVscode(),
  });
  return provider
    .provideDiagnostics(spec, documents)
    .map((diagnostic) => diagnostic.message)
    .filter((message) => !IGNORED_MESSAGES.has(message))
    .filter((message) => !message.startsWith("Could not resolve special param"))
    .sort();
}

const corpus = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "parser-parity.json"), "utf8"),
);

test("diagnostics agree with the real Gauge parser across the parity corpus", () => {
  assert.ok(corpus.length >= 50, "the corpus must stay broad");
  const mismatches = [];
  for (const entry of corpus) {
    const actual = productMessages(entry.text);
    const expected = [...entry.parserErrors].sort();
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      mismatches.push({ label: entry.label, expected, actual });
    }
  }
  assert.deepEqual(mismatches, []);
});

// The concept half of the same corpus. Ground truth is
// parser.CreateConceptsDictionary against a temporary project holding the file,
// which is what the extension's concept diagnostics have to match.
const conceptCorpus = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "concept-parity.json"), "utf8"),
);

function conceptMessages(text) {
  const { GaugeStepDiagnosticsProvider } = require("../src/stepDiagnostics");
  const concept = createDocument(
    text,
    "gauge-concept",
    "/workspace/gauge/specs/concepts/c.cpt",
  );
  const implementation = createDocument(
    IMPLEMENTATIONS,
    "kotlin",
    "/workspace/gauge/src/test/kotlin/Steps.kt",
  );
  const documents = [concept, implementation];
  const provider = new GaugeStepDiagnosticsProvider({
    documentStore: {
      documents: () => documents,
      onDidChangeDocuments: () => ({ dispose() {} }),
      start() {},
    },
    projectFactory: {
      isGaugeProject: () => true,
      getGaugeRootFromFilePath: () => "/workspace/gauge",
    },
    fileSystem: {
      existsSync: () => false,
      readFileSync() {
        throw new Error("no project properties");
      },
      readdirSync() {
        throw new Error("no environment directory");
      },
    },
    pathModule: path.posix,
    vscode: createVscode(),
  });
  return provider
    .provideDiagnostics(concept, documents)
    .map((diagnostic) => diagnostic.message)
    .filter((message) => !IGNORED_MESSAGES.has(message))
    .filter((message) => !message.startsWith("Could not resolve special param"))
    .filter((message) => !message.startsWith("Circular reference found"))
    .sort();
}

test("concept diagnostics agree with the real Gauge concept parser", () => {
  assert.ok(conceptCorpus.length >= 30, "the concept corpus must stay broad");
  const mismatches = [];
  for (const entry of conceptCorpus) {
    const actual = conceptMessages(entry.text);
    const expected = [...entry.parserErrors].sort();
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      mismatches.push({ label: entry.label, expected, actual });
    }
  }
  assert.deepEqual(mismatches, []);
});
